### PR TITLE
Allow line skipping for reading in counts with header lines

### PR DESCRIPTION
**Pull request by vaofford**

### CODE REVIEW

**Review by keiranmraine — APPROVED** [review]
Everything appears to be working as expected, tried both example configs.

**Comment by keiranmraine** [comment]
@vaofford I think I've caught something we need to fix in the docker example (and probably just have in line for both methods).  `--outdir` is not specified in the command so you don't get the result for docker.  For the sake of it being common should the example be updated to append the following to both the native and docker the c-sar commands?

```
--outdir $ANALYSIS_DIR/result
```

**Comment by vaofford** [comment]
@keiranmraine we have it in the default config for the pipeline [nextflow.config](https://github.com/cancerit/C-SAR/blob/develop/nextflow.config):
`outdir = "." `
And then the publishing is done using a variable `resultDir` that is:
`resultDir = "${params.outdir}/results"`
For the examples, that should be overwritten by the `outdir` set in [the example config](https://github.com/cancerit/C-SAR/blob/develop/examples/baggen_2021/baggen_low_stringency.config)
`outdir = '${ANALYSIS_DIR}/results'`
Putting `--outdir` on the command line would be overwriting the same path as is in the example config, so I'm not sure it would solve the issue?

**Comment by keiranmraine** [comment]
> `outdir = '${ANALYSIS_DIR}/results'`

Non interpolating quotes, testing fix and pushing.

**Comment by keiranmraine** [comment]
Now expands as expected:

```
Results directory                       : /.../C-SAR/examples/baggen_2021/results
```

But it still doesn't write any files into this, where in the logs can I see the "copy".

**Review by keiranmraine — CHANGES_REQUESTED** [review]
Something wrong with outdir

**Review by keiranmraine — APPROVED** [review]

**Comment by keiranmraine** [comment]
Decision taken to merge this and investigate the issues with `outdir` elsewhere..

**Pull request merged**
